services:
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    environment:
      - ZIPKIN_HTTP_PORT=9411
    restart: always
    networks:
      - takenseat_network
      
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always
    networks:
      - takenseat_network

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
   #   - ~/grafana/config/grafana.ini:/etc/grafana/grafana.ini
    restart: always
    networks:
      - takenseat_network

  loki:
    image: grafana/loki:3.0.0
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yml:/mnt/config/loki-config.yml
    command: -config.file=/mnt/config/loki-config.yml
    restart: always
    networks:
      - takenseat_network

volumes:
  service_data:
    driver: local
  grafana-storage:

networks:
  takenseat_network:
    name: takenseat_network
    driver: bridge