CREATE DATABASE IF NOT EXISTS auth;
CREATE DATABASE IF NOT EXISTS coupon;
CREATE DATABASE IF NOT EXISTS booking;
CREATE DATABASE IF NOT EXISTS performance;
CREATE DATABASE IF NOT EXISTS payment;
CREATE DATABASE IF NOT EXISTS review;
