global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'gateway-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'gateway-service:19091' ]

  - job_name: 'auth-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'auth-service:19092' ]

  - job_name: 'coupon-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'coupon-service:19093' ]

  - job_name: 'queue-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'queue-service:19094' ]

  - job_name: 'booking-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'booking-service:19095' ]

  - job_name: 'performance-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'performance-service:19096' ]

  - job_name: 'payment-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'payment-service:19097' ]

  - job_name: 'review-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'review-service:19098' ]
